Repository LSW990918/ConcurrencyControlProject, pull requests merged in 2024-02, with the labels that each got.

#4 Feat : BaseTime클래스 생성
  src/main/kotlin/com/a03/concurrencycontrolproject/common/BaseTime.kt
Labels: feature

#6 #5 Feat : user entity생성
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/controller/UserController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/UserResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/model/User.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/repository/UserRole.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/service/UserService.kt
Labels: feature

#13 #5 Fix : SQLDelete, SQLRestriction 어노테이션 추가, var -> val 수정
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/model/User.kt
Labels: feature

#8 #7 Feat : CategoryEntity 생성
  src/main/kotlin/com/a03/concurrencycontrolproject/ConcurrencyControlProjectApplication.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/controller/CetegoryController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/CreateCategoryRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/UpdateCategoryRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/model/Category.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryServiceImpl.kt
Labels: feature

#10 #9 Feat : goods entity 생성
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/goods.kt
Labels: feature

#12 #11 Feat: Review entity 생성
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/Review.kt
Labels: feature

#27 Goods CRUD Dev Merge
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/controller/GoodsController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/CreateGoodsRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/GoodsResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/UpdateGoodsRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/Goods.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/repository/GoodsRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/service/GoodsService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/service/GoodsServiceImpl.kt
Labels: feature

#25 Feature/review
  src/main/kotlin/com/a03/concurrencycontrolproject/common/UserPrincipal.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/dto/CreateReviewRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/dto/ReviewResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/model/Review.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/service/ReviewService.kt
Labels: feature

#29 Feature/user
  src/main/kotlin/com/a03/concurrencycontrolproject/common/security/PasswordEncoderConfig.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/controller/UserController.kt
Labels: bug

#34 #33 Fix : signupRequest -> userRole 삭제
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/SignupRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/model/User.kt
Labels: bug

#36 Refactor : toResponse 함수 dto로 이동
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/CreateGoodsRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/GoodsResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/Goods.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/service/GoodsServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/model/Ticket.kt
Labels: refactor

#39 #37 Refactor : toResponse -> dto로 옮기고 from으로 변경
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/controller/UserController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/UserResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/model/User.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/service/UserService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/service/UserServiceImpl.kt
Labels: refactor

#30 Feature/ticket
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/controller/GoodsController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/dto/TicketResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/model/Ticket.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/CustomTicketRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/TicketRepositoryImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/infra/querydsl/QueryDslSupport.kt
Labels: feature

#41 #40 Refactor : Exception 추가, dto 리펙터링
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/service/ReviewService.kt
Labels: refactor

#45 #44 Feat : Category 페이지네이션 추가
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/model/Category.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/repository/CategoryRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/repository/CategoryRepositoryImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/repository/CustomCategoryRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryServiceImpl.kt
Labels: feature

#47 #44 Feat : CategoryResponse에서 GoodsList 삭제
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/repository/CategoryRepositoryImpl.kt
Labels: refactor

#46 #43 Refactor : ticket 조회 userid 로직 추가
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/model/Ticket.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceImpl.kt
Labels: refactor

#49 Goods 페이지네이션, 동적쿼리 추가, IllegalDateStateException 추가 pull request
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/IllegalDateStateException.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/controller/GoodsController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/CreateGoodsRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/SelectGoodsRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/Goods.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/repository/CustomGoodsRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/repository/CustomGoodsRepositoryImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/repository/GoodsRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/service/GoodsService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/service/GoodsServiceImpl.kt
Labels: feature

#55 #52 Test : Redis 동시성 제어 구현 완료
  build.gradle.kts
  src/main/kotlin/com/a03/concurrencycontrolproject/ConcurrencyControlProjectApplication.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/RedisConfig.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/repository/RedisLockRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedisService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedisServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/dto/GoodsResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/Goods.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceImpl.kt
  src/main/resources/application.yml
  src/test/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceTest.kt
Labels: feature

#57 Feature/redisaop
  build.gradle.kts
  src/main/kotlin/com/a03/concurrencycontrolproject/ConcurrencyControlProjectApplication.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/ConcurrencyControlDto.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/redisson/eventlock/EventLock.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/redisson/eventlock/EventLockAspect.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/redisson/spinlock/RedissonSpinLock.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/redisson/spinlock/RedissonSpinLockAspect.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/spinlock/SpinLock.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/aop/spinlock/SpinLockAspect.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/GlobalExceptionHandler.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/IllegalDateStateException.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/ModelNotFoundException.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/NotExistRoleException.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/exception/WrongEmailOrPasswordException.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/RedisConfig.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/repository/RedisLockRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedisService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedisServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedissonLockService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/common/redis/service/RedissonSpinLockService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/controller/CategoryController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/dto/CategoryResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/model/Category.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/category/service/CategoryService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/goods/model/Goods.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/controller/ReviewController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/dto/UpdateReviewRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/model/Review.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/repository/ReviewQueryDslRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/repository/ReviewQueryDslRepositoryImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/repository/ReviewRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/review/service/ReviewService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/controller/TicketController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/dto/CreateTicketRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/model/Ticket.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/CustomTicketRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/TicketRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/repository/TicketRepositoryImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/controller/UserController.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/LoginRequest.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/LoginResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/dto/UserResponse.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/model/User.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/repository/UserRepository.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/service/UserService.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/domain/user/service/UserServiceImpl.kt
  src/main/kotlin/com/a03/concurrencycontrolproject/infra/swagger/SwaggerConfig.kt
  src/test/kotlin/com/a03/concurrencycontrolproject/SpinLockProjectApplicationTests.kt
  src/test/kotlin/com/a03/concurrencycontrolproject/domain/ticket/service/TicketServiceTest.kt
Labels: feature, refactor, test code
